### ISSUE TITLE
Dead Branches

### ISSUE THREAD

**Issue by mdadamio** [jfox13-nd/Shiver-Me-Tinder#8]
I'm gonna delete some of our one time feature branches and I wanted to make an issue for it 🚀🚀🚀🚀🚀

**Comment by jz543fm** [comment]
Can you assing this issue to me, I will be very happy to this issue.

**Comment by jfox13-nd** [comment]
@jz543fm Thank you for the offer but this is a graded university project so we aren't approving outside PRs at the movement.
